*
* Configuration file for modules in the system
* "board_type" type		- this type must match a definition in XIA_CONFIG
* "module" SCSI_Crate_slot channel0 channel1 channel2 channel3
* "default_dsp" filename
* "dsp" channel filename
* "default_fippi" filename
* "fippi" channel filename
* "default_param" filename
* "param" channel filename
*
* All dsp, fippi and param definitions must follow the module definition 
* that they apply to.
*
* the board_type must be defined prior to defining the module information
* it will apply to all future module definitions until the tag is reused.
*
* the iolibrary name must be defined before the interface library is defined
* if a new interface is defined, the iolibrary must be named before in all 
* cases.
*
board_type   dxpx10p
iolibrary    0x378
interface    EPP
module  0 0
default_fippi  FIPPI_DEFAULT
default_dsp    x10p0106.hex
default_param  x10p.cfg
