/* xia_version.h -- DO NOT MODIFY
 *
 * This file automatically generated by 
 * build_helpers.version on 2010-11-10 10:14:55.415000
 */

#ifndef __XIA_VERSION_H__
#define __XIA_VERSION_H__

#define XERXES_MAJOR_VERSION 1
#define XERXES_MINOR_VERSION 1
#define XERXES_RELEASE_VERSION 5

#define HANDEL_MAJOR_VERSION 1
#define HANDEL_MINOR_VERSION 1
#define HANDEL_RELEASE_VERSION 5

#define VERSION_STRING "beta"

#endif /* __XIA_VERSION_H__ */

