/* xia_version.h -- DO NOT MODIFY
 *
 * This file automatically generated by 
 * build_helpers.version on 2011-03-23 20:52:29.700000
 */

#ifndef __XIA_VERSION_H__
#define __XIA_VERSION_H__

#define XERXES_MAJOR_VERSION 1
#define XERXES_MINOR_VERSION 1
#define XERXES_RELEASE_VERSION 10

#define HANDEL_MAJOR_VERSION 1
#define HANDEL_MINOR_VERSION 1
#define HANDEL_RELEASE_VERSION 10

#define VERSION_STRING "release"

#endif /* __XIA_VERSION_H__ */

